-- Dọc Bờ — seed data (chạy SAU 01_schema.sql)
-- An toàn khi chạy lại: xoá sạch rồi nạp mới.
truncate table public.places;
delete from public.provinces;
delete from public.types;

insert into public.types (key,label,color) values
  ('view','Cảnh đẹp','#0e7c86'),
  ('food','Ăn uống','#e5643c'),
  ('stay','Lưu trú','#4e8c5a');

insert into public.provinces (key,name,center_lat,center_lng,region,sort_order) values
  ('hg','Hà Giang',23.0,105.15,'Đông Bắc',0),
  ('cb','Cao Bằng',22.75,106.4,'Đông Bắc',1),
  ('ls','Lạng Sơn',21.85,106.76,'Đông Bắc',2),
  ('tq','Tuyên Quang',22.05,105.35,'Đông Bắc',3),
  ('bk','Bắc Kạn',22.3,105.72,'Đông Bắc',4),
  ('tn','Thái Nguyên',21.59,105.84,'Đông Bắc',5),
  ('db','Điện Biên',21.39,103.02,'Tây Bắc',6),
  ('sl','Sơn La',20.95,104.55,'Tây Bắc',7),
  ('hb','Hòa Bình',20.73,105.15,'Tây Bắc',8),
  ('qn','Quảng Ninh',20.95,107.1,'Duyên hải Bắc Bộ',9),
  ('hp','Hải Phòng',20.84,106.69,'Duyên hải Bắc Bộ',10),
  ('ht','Hà Tĩnh',18.2,106.3,'Miền Trung',11),
  ('qb','Quảng Bình',17.55,106.55,'Miền Trung',12),
  ('qt','Quảng Trị',17.0,107.05,'Miền Trung',13),
  ('hue','Huế',16.4,107.7,'Miền Trung',14),
  ('dn','Đà Nẵng–Hội An',16.05,108.2,'Miền Trung',15),
  ('qng','Quảng Ngãi',15.1,108.75,'Miền Trung',16),
  ('bd','Bình Định',13.8,109.25,'Miền Trung',17),
  ('py','Phú Yên',13.05,109.33,'Miền Trung',18),
  ('kh','Nha Trang',12.2388,109.1967,'Ven biển Nam',19),
  ('nt','Ninh Thuận',11.5645,108.99,'Ven biển Nam',20),
  ('bt','Bình Thuận',10.93,108.1,'Ven biển Nam',21),
  ('vt','Vũng Tàu',10.4113,107.1362,'Ven biển Nam',22);

insert into public.places (name,type,province,lat,lng,note,tel,map_url,status) values
  ('Cột cờ Lũng Cú','view','hg',23.3624,105.3138,'Điểm cực Bắc Tổ quốc, cột cờ trên đỉnh núi Rồng.',NULL,NULL,'published'),
  ('Đèo Mã Pí Lèng','view','hg',23.2247,105.332,'Một trong tứ đại đỉnh đèo, nhìn xuống sông Nho Quế.',NULL,NULL,'published'),
  ('Sông Nho Quế – Hẻm Tu Sản','view','hg',23.205,105.345,'Đi thuyền ngắm hẻm vực sâu nhất Đông Nam Á.',NULL,NULL,'published'),
  ('Phố cổ Đồng Văn','view','hg',23.278,105.362,'Phố cổ gần thế kỷ, nhâm nhi cà phê phố cổ.',NULL,NULL,'published'),
  ('Dinh thự Vua Mèo (Nhà Vương)','view','hg',23.2756,105.27,'Dinh họ Vương ở Sà Phìn, đầu thế kỷ 20.',NULL,NULL,'published'),
  ('Cổng trời & Núi đôi Quản Bạ','view','hg',23.076,105.001,'View thung lũng Tam Sơn, núi đôi Cô Tiên.',NULL,NULL,'published'),
  ('Sủng Là – Nhà của Pao','view','hg',NULL,NULL,'Làng bối cảnh phim ‘Chuyện của Pao’.',NULL,NULL,'published'),
  ('Dốc Thẩm Mã','view','hg',NULL,NULL,'Dốc cua tay áo nổi tiếng để check-in.',NULL,NULL,'published'),
  ('Ruộng bậc thang Hoàng Su Phì','view','hg',NULL,NULL,'Di sản ruộng bậc thang, đẹp mùa lúa chín.',NULL,NULL,'published'),
  ('Thác Bản Giốc','view','cb',22.853,106.723,'Thác đẹp nhất VN, nằm trên biên giới Việt–Trung.',NULL,NULL,'published'),
  ('Động Ngườm Ngao','view','cb',22.847,106.705,'Hang động đẹp bậc nhất miền Bắc, sát Bản Giốc.',NULL,NULL,'published'),
  ('Khu di tích Pác Bó','view','cb',22.976,106.1,'Suối Lê Nin, hang Cốc Bó gắn với Bác Hồ.',NULL,NULL,'published'),
  ('Hồ Thang Hen','view','cb',NULL,NULL,'Hồ trên núi nước xanh ngọc, mùa nước đẹp.',NULL,NULL,'published'),
  ('Núi Mắt Thần','view','cb',NULL,NULL,'Núi thủng độc đáo bên thảo nguyên Quây Sơn.',NULL,NULL,'published'),
  ('Làng rèn Phúc Sen','view','cb',NULL,NULL,'Làng nghề rèn dao truyền thống của người Nùng.',NULL,NULL,'published'),
  ('Đèo Mã Phục','view','cb',22.65,106.45,'Đèo 7 tầng đẹp trên đường tới Bản Giốc.',NULL,NULL,'published'),
  ('Hồ Bản Viết','view','cb',NULL,NULL,'Hồ giữa rừng, mùa thu lá đỏ.',NULL,NULL,'published'),
  ('Di tích Chiến thắng Đông Khê','view','cb',NULL,NULL,'Di tích chiến dịch Biên giới 1950.',NULL,NULL,'published'),
  ('Phở chua Cao Bằng','food','cb',NULL,NULL,'Phở chua trộn đặc sản.',NULL,NULL,'published'),
  ('Vịt quay 7 vị – hạt dẻ Trùng Khánh','food','cb',NULL,NULL,'Vịt quay 7 vị, hạt dẻ Trùng Khánh.',NULL,NULL,'published'),
  ('Bánh cuốn Cao Bằng','food','cb',NULL,NULL,'Bánh cuốn chan nước xương nóng.',NULL,NULL,'published'),
  ('Động & chùa Tam Thanh','view','ls',21.858,106.753,'Động đá vôi có chùa, phù điêu A Di Đà thế kỷ XVII.',NULL,NULL,'published'),
  ('Núi Tô Thị – Thành nhà Mạc','view','ls',21.859,106.751,'Tượng đá nàng Tô Thị, thành cổ thế kỷ XVI.',NULL,NULL,'published'),
  ('Đỉnh Mẫu Sơn','view','ls',21.85,107.09,'Núi cao mát lạnh, mùa đông có băng tuyết.',NULL,NULL,'published'),
  ('Đền Mẫu Đồng Đăng','view','ls',21.956,106.706,'Đền thờ Mẫu nổi tiếng gần cửa khẩu Hữu Nghị.',NULL,NULL,'published'),
  ('Thung lũng hoa Bắc Sơn','view','ls',NULL,NULL,'Lúa vàng + đồng hoa, view từ núi Nà Lay.',NULL,NULL,'published'),
  ('Thảo nguyên Đồng Lâm','view','ls',NULL,NULL,'‘Vịnh Hạ Long trên cạn’ ở Hữu Lũng, cắm trại.',NULL,NULL,'published'),
  ('Ải Chi Lăng','view','ls',NULL,NULL,'Cửa ải lịch sử hiểm trở.',NULL,NULL,'published'),
  ('Chợ Đông Kinh','view','ls',NULL,NULL,'Chợ lớn nhất xứ Lạng, hàng hoá phong phú.',NULL,NULL,'published'),
  ('Khu di tích Tân Trào','view','tq',21.84,105.42,'Thủ đô kháng chiến: lán Nà Nưa, cây đa Tân Trào.',NULL,NULL,'published'),
  ('Khu sinh thái Na Hang','view','tq',22.49,105.39,'Hồ thuỷ điện, núi non — ‘Hạ Long trên núi’.',NULL,NULL,'published'),
  ('Suối khoáng Mỹ Lâm','view','tq',NULL,NULL,'Suối khoáng nóng để nghỉ dưỡng.',NULL,NULL,'published'),
  ('Thác Bản Ba','view','tq',NULL,NULL,'Thác nhiều tầng giữa rừng Chiêm Hoá.',NULL,NULL,'published'),
  ('Thác Mơ (Pác Ban)','view','tq',22.5,105.38,'Thác 3 tầng giữa khu Na Hang, đi đò trên hồ.',NULL,NULL,'published'),
  ('Núi & đền Pác Tạ','view','tq',22.5,105.4,'Núi hình voi cúi đầu, đền cổ linh thiêng ven hồ.',NULL,NULL,'published'),
  ('Đình Tân Trào','view','tq',21.84,105.42,'Nơi họp Quốc dân Đại hội tháng 8/1945.',NULL,NULL,'published'),
  ('99 ngọn núi Thượng Lâm','view','tq',NULL,NULL,'‘Hạ Long giữa đại ngàn’ ở Lâm Bình.',NULL,NULL,'published'),
  ('Thác Khuổi Nhi','view','tq',NULL,NULL,'Thác 3 tầng, thả chân cho cá massage.',NULL,NULL,'published'),
  ('Cọc Vài Phạ','view','tq',NULL,NULL,'Cọc đá giữa hồ Na Hang gắn truyền thuyết Tài Ngào.',NULL,NULL,'published'),
  ('Bảo tàng Tuyên Quang','view','tq',NULL,NULL,'Hiện vật lịch sử – văn hoá xứ Tuyên.',NULL,NULL,'published'),
  ('Gỏi cá bỗng sông Lô','food','tq',NULL,NULL,'Đặc sản cá bỗng tươi sông Lô.',NULL,NULL,'published'),
  ('Bánh cuốn Tuyên Quang','food','tq',NULL,NULL,'Bánh cuốn nóng ăn ở chợ đêm.',NULL,NULL,'published'),
  ('Hồ Ba Bể','view','bk',22.402,105.617,'Hồ nước ngọt tự nhiên lớn nhất VN, giữa VQG Ba Bể.',NULL,NULL,'published'),
  ('Động Puông','view','bk',22.44,105.63,'Sông Năng xuyên núi đá vôi, hang dơi dài 300m.',NULL,NULL,'published'),
  ('Thác Đầu Đẳng','view','bk',22.38,105.55,'Thác 3 tầng hơn 1.000m trên sông Năng.',NULL,NULL,'published'),
  ('Ao Tiên','view','bk',22.41,105.63,'Hồ nhỏ nước trong giữa lòng chảo đá vôi, cạnh hồ Ba Bể.',NULL,NULL,'published'),
  ('Đảo Bà Góa','view','bk',22.4,105.61,'Đảo đá phủ cây xanh giữa hồ Ba Bể.',NULL,NULL,'published'),
  ('Đền An Mã','view','bk',22.4,105.62,'Đền trên đảo đá giữa hồ, thờ Mẫu Thượng Ngàn.',NULL,NULL,'published'),
  ('Động Hua Mạ','view','bk',22.36,105.63,'‘Kỳ quan trong lòng đất’, thạch nhũ lộng lẫy.',NULL,NULL,'published'),
  ('Bản Pác Ngòi','view','bk',22.39,105.62,'Bản Tày nhà sàn cổ ven hồ, homestay, hát then.',NULL,NULL,'published'),
  ('Suối Bó Lòm','view','bk',22.29767728879754,105.55826393019761,'Suối giữa rừng vùng Ba Bể (toạ độ do bạn cung cấp).',NULL,NULL,'published'),
  ('Động Nàng Tiên','view','bk',NULL,NULL,'Động tự nhiên sâu ~60m ở Na Rì.',NULL,NULL,'published'),
  ('Thác Nà Khoang','view','bk',NULL,NULL,'Thác bậc thang giữa rừng, sơn thủy hữu tình.',NULL,NULL,'published'),
  ('Cá nướng Pác Ngòi','food','bk',NULL,NULL,'Cá hồ Ba Bể nướng than, ăn tại bản Pác Ngòi.',NULL,NULL,'published'),
  ('Lẩu cá hồ Ba Bể','food','bk',NULL,NULL,'Lẩu cá tươi đánh bắt trên hồ.',NULL,NULL,'published'),
  ('Bánh trứng kiến','food','bk',NULL,NULL,'Bánh lá vả nhân trứng kiến của người Tày (mùa xuân).',NULL,NULL,'published'),
  ('Miến dong Na Rì','food','bk',NULL,NULL,'Miến dong dai ngon, đặc sản mua làm quà.',NULL,NULL,'published'),
  ('Gà đồi nướng Ba Bể','food','bk',NULL,NULL,'Gà thả rông nướng than, ăn kèm xôi nếp nương.',NULL,NULL,'published'),
  ('Hồ Núi Cốc','view','tn',21.545,105.717,'‘Vịnh Hạ Long trên cạn’, truyền thuyết nàng Công – chàng Cốc.',NULL,NULL,'published'),
  ('Đồi chè Tân Cương','view','tn',21.545,105.76,'Vùng ‘đệ nhất danh trà’, đồi chè xanh mướt, hái chè.',NULL,NULL,'published'),
  ('Hang Phượng Hoàng – Suối Mỏ Gà','view','tn',21.78,106.05,'Hang 3 tầng nhũ đá + suối nước mát (Võ Nhai).',NULL,NULL,'published'),
  ('ATK Định Hóa','view','tn',21.9,105.63,'Thủ đô kháng chiến, di tích lán Bác Hồ, đồi Khau Tý.',NULL,NULL,'published'),
  ('Thác Khuôn Tát','view','tn',21.92,105.6,'Thác bạc 7 tầng, đầu nguồn suối Tỉn Keo (Định Hóa).',NULL,NULL,'published'),
  ('Bảo tàng Văn hóa các dân tộc VN','view','tn',21.593,105.843,'Lưu giữ bản sắc 54 dân tộc, TP Thái Nguyên.',NULL,NULL,'published'),
  ('Đền Đuổm','view','tn',21.72,105.7,'Đền thờ Dương Tự Minh dưới núi Đuổm (Phú Lương).',NULL,NULL,'published'),
  ('Làng nhà sàn Thái Hải','view','tn',21.52,105.8,'Bản Tày Nùng tái hiện, được UNWTO vinh danh.',NULL,NULL,'published'),
  ('Núi Văn – Núi Võ','view','tn',NULL,NULL,'Hai núi thiêng gắn truyền thuyết, view vùng chè (Đại Từ).',NULL,NULL,'published'),
  ('Hồ Ghềnh Chè','view','tn',NULL,NULL,'Hồ giữa đồi chè, cắm trại, chèo thuyền (Sông Công).',NULL,NULL,'published'),
  ('Đường hầm Pháp','view','tn',NULL,NULL,'Di tích đường hầm khai thác mỏ thời Pháp, xã Yên Thịnh.',NULL,NULL,'published'),
  ('Đường dây tời quặng Pháp','view','tn',NULL,NULL,'Hệ thống tời quặng thời Pháp, xã Yên Thịnh.',NULL,NULL,'published'),
  ('Trà Tân Cương','food','tn',NULL,NULL,'Đặc sản ‘đệ nhất danh trà’, mua tại vườn Tân Cương.',NULL,NULL,'published'),
  ('Bánh chưng Bờ Đậu','food','tn',NULL,NULL,'Bánh chưng nếp Định Hóa gói lá dong, làng Bờ Đậu.',NULL,NULL,'published'),
  ('Nem chua Đại Từ','food','tn',NULL,NULL,'Nem chua nướng/áp chảo, đặc sản Đại Từ.',NULL,NULL,'published'),
  ('Cơm lam – bánh ngải','food','tn',NULL,NULL,'Cơm lam ống tre, bánh ngải lá ngải cứu của người Tày.',NULL,NULL,'published'),
  ('Bánh cooc mò','food','tn',NULL,NULL,'Bánh gạo nếp hình sừng bò, dẻo ngọt.',NULL,NULL,'published'),
  ('Di tích Chiến trường Điện Biên Phủ','view','db',21.387,103.009,'Đồi A1, hầm Đờ Cát, Bảo tàng Chiến thắng.',NULL,NULL,'published'),
  ('Tượng đài Chiến thắng Điện Biên Phủ','view','db',21.388,103.019,'Tượng đồng lớn trên đồi D1.',NULL,NULL,'published'),
  ('Đèo Pha Đin','view','db',21.49,103.31,'Một trong tứ đại đỉnh đèo Tây Bắc.',NULL,NULL,'published'),
  ('Sở chỉ huy Mường Phăng','view','db',NULL,NULL,'Hầm Đại tướng Võ Nguyên Giáp giữa rừng.',NULL,NULL,'published'),
  ('A Pa Chải','view','db',NULL,NULL,'Cực Tây Tổ quốc, ngã ba biên giới Việt–Lào–Trung.',NULL,NULL,'published'),
  ('Hồ Pá Khoang','view','db',21.43,103.15,'Hồ giữa rừng, gần Mường Phăng.',NULL,NULL,'published'),
  ('Cánh đồng Mường Thanh','view','db',21.38,103.02,'Vựa lúa lớn nhất Tây Bắc.',NULL,NULL,'published'),
  ('Cao nguyên đá Tủa Chùa','view','db',NULL,NULL,'Cao nguyên đá, ruộng bậc thang, chợ phiên.',NULL,NULL,'published'),
  ('Suối khoáng nóng U Va','view','db',NULL,NULL,'Suối khoáng nóng của người Thái.',NULL,NULL,'published'),
  ('Thành Bản Phủ','view','db',NULL,NULL,'Thành cổ + đền Hoàng Công Chất.',NULL,NULL,'published'),
  ('Xôi nếp nương – gà đen','food','db',NULL,NULL,'Xôi nếp nương, gà đen, pa pỉnh tộp.',NULL,NULL,'published'),
  ('Cao nguyên Mộc Châu','view','sl',20.834,104.636,'Đồi chè, đồng hoa mận–cải, vườn dâu tây.',NULL,NULL,'published'),
  ('Đồi chè trái tim Mộc Châu','view','sl',20.85,104.68,'Đồi chè tạo hình trái tim nổi tiếng.',NULL,NULL,'published'),
  ('Thác Dải Yếm','view','sl',20.817,104.608,'Thác trắng giữa Mộc Châu, có cầu kính.',NULL,NULL,'published'),
  ('Nhà tù Sơn La','view','sl',21.329,103.905,'Di tích nhà tù Pháp, cây đào Tô Hiệu.',NULL,NULL,'published'),
  ('Sống lưng khủng long Tà Xùa','view','sl',NULL,NULL,'Sống núi săn mây nổi tiếng.',NULL,NULL,'published'),
  ('Hang Dơi (Sơn Mộc Hương)','view','sl',20.85,104.65,'‘Tây thiên đệ nhất động’ ở Mộc Châu.',NULL,NULL,'published'),
  ('Rừng thông bản Áng','view','sl',20.82,104.7,'Hồ + rừng thông, cắm trại, cưỡi ngựa.',NULL,NULL,'published'),
  ('Cầu kính Bạch Long','view','sl',20.8,104.62,'Cầu kính dài kỷ lục ở Mộc Châu.',NULL,NULL,'published'),
  ('Ngọc Chiến','view','sl',NULL,NULL,'Bản Thái, suối khoáng nóng, ruộng bậc thang (Mường La).',NULL,NULL,'published'),
  ('Bê chao Mộc Châu','food','sl',NULL,NULL,'Đặc sản bê chao + sữa Mộc Châu.',NULL,NULL,'published'),
  ('Cá hồi – cá tầm Mộc Châu','food','sl',NULL,NULL,'Trại cá nước lạnh, lẩu cá hồi.',NULL,NULL,'published'),
  ('Mai Châu – Bản Lác','view','hb',20.661,105.1,'Bản người Thái, nhà sàn, ruộng lúa, đạp xe.',NULL,NULL,'published'),
  ('Hồ Hòa Bình','view','hb',20.81,105.33,'Hồ thuỷ điện rộng lớn, du thuyền, Thung Nai.',NULL,NULL,'published'),
  ('Đèo Thung Khe','view','hb',NULL,NULL,'Đèo Đá Trắng mây mù, ngô & trứng nướng ven đường.',NULL,NULL,'published'),
  ('Suối khoáng Kim Bôi','view','hb',NULL,NULL,'Suối khoáng nóng nghỉ dưỡng.',NULL,NULL,'published'),
  ('Thác Mu','view','hb',20.43,105.42,'Thác nhiều tầng nước xanh ngọc, có hang Mu (Lạc Sơn).',NULL,NULL,'published'),
  ('Thung Nai','view','hb',20.77,105.24,'‘Vịnh Hạ Long trên núi’, du thuyền sông Đà.',NULL,NULL,'published'),
  ('Cửu Thác Tú Sơn','view','hb',NULL,NULL,'Khu 9 tầng thác, tắm suối (Kim Bôi).',NULL,NULL,'published'),
  ('Thác Gò Lào','view','hb',NULL,NULL,'Thác ~20m giữa rừng, gần Mai Châu.',NULL,NULL,'published'),
  ('Hang Kia – Pà Cò','view','hb',NULL,NULL,'Săn mây, vườn mận đào, bản người Mông.',NULL,NULL,'published'),
  ('Lũng Vân','view','hb',NULL,NULL,'‘Nóc nhà xứ Mường’, bản vùng cao mây phủ.',NULL,NULL,'published'),
  ('Bảo tàng Không gian Văn hoá Mường','view','hb',NULL,NULL,'Tái hiện đời sống người Mường (TP Hòa Bình).',NULL,NULL,'published'),
  ('Cơm lam – lợn mán','food','hb',NULL,NULL,'Cơm lam ống tre, thịt lợn mán nướng.',NULL,NULL,'published'),
  ('Vịnh Hạ Long','view','qn',20.91,107.184,'Di sản UNESCO, hàng nghìn đảo đá vôi.',NULL,NULL,'published'),
  ('Bãi Cháy','view','qn',20.954,107.07,'Khu du lịch biển, Sun World, cáp treo Nữ Hoàng.',NULL,NULL,'published'),
  ('Núi Yên Tử','view','qn',21.156,106.723,'Kinh đô Phật giáo Trúc Lâm, chùa Đồng trên đỉnh.',NULL,NULL,'published'),
  ('Đảo Cô Tô','view','qn',20.976,107.767,'Đảo biển nước trong xanh, cát trắng.',NULL,NULL,'published'),
  ('Đảo Quan Lạn','view','qn',NULL,NULL,'Đảo hoang sơ, bãi Minh Châu.',NULL,NULL,'published'),
  ('Trà Cổ – Móng Cái','view','qn',NULL,NULL,'Bãi biển dài gần biên giới.',NULL,NULL,'published'),
  ('Hang Sửng Sốt','view','qn',20.85,107.1,'Hang lớn đẹp nhất vịnh Hạ Long.',NULL,NULL,'published'),
  ('Đảo Ti Tốp','view','qn',20.83,107.08,'Bãi tắm + đỉnh ngắm toàn vịnh.',NULL,NULL,'published'),
  ('Vịnh Bái Tử Long','view','qn',21.0,107.5,'Vịnh hoang sơ cạnh Hạ Long.',NULL,NULL,'published'),
  ('Chùa Ba Vàng','view','qn',21.08,106.78,'Chùa lớn trên núi Thành Đẳng (Uông Bí).',NULL,NULL,'published'),
  ('Bảo tàng Quảng Ninh','view','qn',20.95,107.09,'‘Cung điện’ kính đen soi bóng vịnh.',NULL,NULL,'published'),
  ('Chả mực Hạ Long','food','qn',NULL,NULL,'Chả mực giã tay, ăn với xôi/bánh cuốn.',NULL,NULL,'published'),
  ('Đảo Cát Bà','view','hp',20.728,107.048,'Đảo lớn, vườn quốc gia, nhiều bãi tắm.',NULL,NULL,'published'),
  ('Vịnh Lan Hạ','view','hp',20.7,107.07,'Vịnh đẹp cạnh Cát Bà, kayak & tắm biển.',NULL,NULL,'published'),
  ('Biển Đồ Sơn','view','hp',20.714,106.779,'Khu nghỉ biển lâu đời, lễ hội chọi trâu.',NULL,NULL,'published'),
  ('Bánh đa cua bể Bà Cụ – Cầu Đất','food','hp',NULL,NULL,'Bánh đa cua trứ danh, hẻm 195 Cầu Đất.',NULL,NULL,'published'),
  ('Bánh đa cua Kỳ Đồng','food','hp',NULL,NULL,'26 Kỳ Đồng — nước cua đồng ngọt thanh.',NULL,NULL,'published'),
  ('Bánh đa cua 48 Lạch Tray','food','hp',NULL,NULL,'48 Lạch Tray — quán đông khách quen.',NULL,NULL,'published'),
  ('Bánh mì cay Ông Cuông','food','hp',NULL,NULL,'184 Hàng Kênh — bánh mì que pate, chí chương cay.',NULL,NULL,'published'),
  ('Bánh mì cay Lê Hoàng','food','hp',NULL,NULL,'39 Đinh Tiên Hoàng — bánh mì que nổi tiếng.',NULL,NULL,'published'),
  ('Nem cua bể Thuận Yến','food','hp',NULL,NULL,'88 Trần Nhật Duật — nem cua bể vuông giòn rụm.',NULL,NULL,'published'),
  ('Nem cua bể Nga','food','hp',NULL,NULL,'92 Trần Nhật Duật — nem hải sản trứ danh.',NULL,NULL,'published'),
  ('Ốc Thủy Dương','food','hp',NULL,NULL,'30/263 Lạch Tray — thiên đường ốc, mở chiều tối.',NULL,NULL,'published'),
  ('Ốc chị Hoa','food','hp',NULL,NULL,'69 Máy Tơ — quán ốc bình dân đông khách.',NULL,NULL,'published'),
  ('Bún cá cay Lê Lợi','food','hp',NULL,NULL,'66 Lê Lợi — bún cá cay chuẩn vị đất Cảng.',NULL,NULL,'published'),
  ('Giá bể xào Huệ Béo','food','hp',NULL,NULL,'103 Dư Hàng — giá bể (giá biển) xào đặc sản.',NULL,NULL,'published'),
  ('Sủi dìn & chè Cô Út','food','hp',NULL,NULL,'163-165 Cầu Đất — sủi dìn, bơ dầm, chè vừng.',NULL,NULL,'published'),
  ('Dừa dầm Cô Tuyến','food','hp',NULL,NULL,'100/124 Lạch Tray — dừa dầm mát lạnh.',NULL,NULL,'published'),
  ('Chợ Cố Đạo (ăn vặt)','food','hp',NULL,NULL,'78 Trần Nhật Duật — thiên đường ăn vặt chiều tối.',NULL,NULL,'published'),
  ('Pate cột đèn','food','hp',NULL,NULL,'Pate gan truyền thống, mua làm quà.',NULL,NULL,'published'),
  ('Thiên Cầm','view','ht',18.34,106.1,'Điểm vào tuyến biển Hà Tĩnh. Mẹo: đừng ăn ngay Thiên Cầm, chạy thêm tới Kỳ Xuân.',NULL,NULL,'published'),
  ('Cầu Cửa Nhượng','view','ht',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/QUydHETRMHBcN6HNA','published'),
  ('Hải đăng Cửa Nhượng','view','ht',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/T6bxfv1Fpf75sGfS8','published'),
  ('Nhà hàng Hải Đăng Tình Lành','food','ht',NULL,NULL,'Phía sau ngọn hải đăng, Cẩm Trung.','0968540598','https://maps.app.goo.gl/Zgf4hRDr4RqJzpu7A','published'),
  ('Đường ven biển Kỳ Bắc','view','ht',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/R5GVSosEeznNEpSf9','published'),
  ('Bãi biển Cu Kỳ — Kỳ Xuân','view','ht',18.18,106.3,'Có lều nghỉ, võng nằm, cảnh đẹp, cắm trại ok, hải sản tươi (chế biến bình thường).','0977976678','https://maps.app.goo.gl/j7xAo2KcYHBEnc3w6','published'),
  ('Bãi biển Kỳ Xuân','view','ht',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/6XCGwM5M9dmtTwrU7','published'),
  ('Nhà hàng & Homestay Phương Đức','stay','ht',NULL,NULL,'Chân biển Kỳ Xuân, có homestay view biển cực chill.','0964588777','https://maps.app.goo.gl/ohqVbjva9fLwxJ1YA','published'),
  ('Rì Rào Homestay Kỳ Xuân','stay','ht',NULL,NULL,'Thắng Lợi, Kỳ Xuân.',NULL,'https://maps.app.goo.gl/MsGZi1Vt8HVvzKz86','published'),
  ('Nhà hàng Thế Giới Mực Nhảy','food','ht',NULL,NULL,'Xuân Thắng, Kỳ Xuân.','0964890369','https://maps.app.goo.gl/6r6wv7feHPFHhYg19','published'),
  ('Bếp dã ngoại Kỳ Xuân','food','ht',NULL,NULL,'Phải kéo đồ một đoạn.','0978822543','https://maps.app.goo.gl/gXz3bGTDmTtE8Yfq5','published'),
  ('Hải sản Bao Cấp 1994','food','ht',NULL,NULL,'Quán ruột ở Kỳ Xuân, dân địa phương hay ăn.','0358571276','https://maps.app.goo.gl/fmjzCHmVuPMQHxQE8','published'),
  ('Nhà hàng Hải Sản Dân Hường','food','ht',NULL,NULL,NULL,'0919973458','https://maps.app.goo.gl/vBGEMQzyY98Ni95N9','published'),
  ('LIMDIM Hotel','stay','ht',NULL,NULL,'Kỳ Xuân.','0971560642','https://maps.app.goo.gl/ZhWccgYaqUkzc1Sw6','published'),
  ('Nhà nghỉ Phương Nam','stay','ht',NULL,NULL,'Sơn Tịnh, Kỳ Xuân.','0972520420','https://maps.app.goo.gl/qwZbkxLv3wtenze37','published'),
  ('Bãi biển Nguyễn Huệ — Kỳ Xuân','view','ht',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/TRqUSdQ81hLsb39j6','published'),
  ('Eo biển Kỳ Xuân – Kỳ Phú','view','ht',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/ZoCn26Bf4cMMnMZ2A','published'),
  ('Đường quốc phòng ven biển Xuân Hội','view','ht',NULL,NULL,'Kỳ Khang.',NULL,'https://maps.app.goo.gl/YdNLaWsGaAxUJKLW9','published'),
  ('Quảng trường biển Kỳ Ninh','view','ht',NULL,NULL,'Kỳ Anh.',NULL,'https://maps.app.goo.gl/Lo8TA53yeD5BbknEA','published'),
  ('Homestay View Biển — Kỳ Nam','stay','ht',NULL,NULL,'Kỳ Nam, Kỳ Anh. Gặp em Hương.','0963345335','https://maps.app.goo.gl/1CJBSWrU3vegdFg96','published'),
  ('Nhà hàng Ra Khơi','food','ht',NULL,NULL,'Đường ven biển Hoành Sơn.','0973266579','https://maps.app.goo.gl/ocEDwm11LDtnx3Lz5','published'),
  ('Nhà hàng – Khách sạn Hoành Sơn','stay','ht',NULL,NULL,NULL,'0973531430','https://maps.app.goo.gl/irkKmi72A7Z5LpJr7','published'),
  ('Bãi biển Hoành Sơn','view','ht',18.07,106.5,'Gần Hoành Sơn Quan – Đèo Ngang.',NULL,'https://maps.app.goo.gl/MqQ5vtWhfaP96LFaA','published'),
  ('Hoành Sơn Quán','food','ht',NULL,NULL,NULL,'0967825852','https://maps.app.goo.gl/Qd8dZr2JEJDBEdKu7','published'),
  ('Camping bãi biển Kỳ Anh','view','ht',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/mYqhvD2FSw6w59bu6','published'),
  ('Mực nháy Vũng Áng – NH Hậu Thìn','food','ht',NULL,NULL,'Ở cuối bãi biển.','0978957599','https://maps.app.goo.gl/shmGsDDTs3kuCXhj6','published'),
  ('KS Hoàng Anh — Kỳ Thịnh','stay','ht',NULL,NULL,'Chỗ ngủ khi phải ở lại Vũng Áng.','0967855509','https://maps.app.goo.gl/eTGTPeQSH6SyFT2P9','published'),
  ('Ngã ba Đồng Lộc','view','ht',18.5083,105.6469,'Di tích 10 nữ TNXP — nằm sâu trong đất liền, tiện đường thì rẽ vào.',NULL,NULL,'published'),
  ('Chùa Hương Tích (Hà Tĩnh)','view','ht',18.3589,105.7028,'‘Hoan Châu đệ nhất danh lam’ trên núi Hồng Lĩnh.',NULL,NULL,'published'),
  ('Khu di tích Nguyễn Du — Tiên Điền','view','ht',NULL,NULL,'Khu lưu niệm đại thi hào Nguyễn Du.',NULL,NULL,'published'),
  ('Biển Vũng Chùa — mộ Đại tướng Giáp','view','qb',17.91,106.5,NULL,NULL,'https://maps.app.goo.gl/Yjz8cTPSrZEkq6Sf7','published'),
  ('Nhà hàng & Homestay Hoa Biển','stay','qb',NULL,NULL,'Gần mộ Đại tướng.','0908423410',NULL,'published'),
  ('Cảnh Dương Beach','view','qb',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/vAayVrQGaenmGofs8','published'),
  ('Bãi tắm Cảnh Dương','view','qb',NULL,NULL,'Cảnh Thượng, Quảng Trạch.',NULL,'https://maps.app.goo.gl/wyv9RL1ADBgvx9cWA','published'),
  ('Bãi biển Quảng Thọ','view','qb',NULL,NULL,'Bắc Gianh.',NULL,'https://maps.app.goo.gl/3oPDb7tiAQCU3e8MA','published'),
  ('Bãi Đá Nhảy — Lý Hòa','view','qb',17.65,106.45,'Bãi đá kỳ thú sát QL1A, Bố Trạch.',NULL,'https://maps.app.goo.gl/3s6cQEEzpDdsvgXA8','published'),
  ('Bãi biển Đá Nhảy — Thanh Trạch','view','qb',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/pqRhuALjoCoCj8cV6','published'),
  ('Đá Nhảy Beach Hotel','stay','qb',NULL,NULL,NULL,'0848445444','https://maps.app.goo.gl/b6MVNyA9vk9zxfh28','published'),
  ('Bãi Đá Nhảy (phía sau)','view','qb',NULL,NULL,'Lý Hòa, Bố Trạch.',NULL,'https://maps.app.goo.gl/6FSbQyMzaVhiShY56','published'),
  ('Camping bãi Đá Nhảy','view','qb',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/48BYHQTG9sB4Jya58','published'),
  ('Khách sạn Hoài Thu','stay','qb',NULL,NULL,'Bắc Trạch.','0348740959','https://maps.app.goo.gl/MMbBN6xACWF3p9sy5','published'),
  ('Khách sạn An Bình','stay','qb',NULL,NULL,'Xóm Cồn, Bắc Gianh.','0912414121','https://maps.app.goo.gl/12fY5JHVjtkNv19J9','published'),
  ('Cường Thu Nhà Nghỉ','stay','qb',NULL,NULL,'Quyết Thắng, Bắc Trạch.','0949094004','https://maps.app.goo.gl/7PtWfvkqV2hpNoKY6','published'),
  ('Khách sạn Hoài Thu 2','stay','qb',NULL,NULL,'Bắc Trạch.','0348740959','https://maps.app.goo.gl/2HrV5Kn5bPv5aDxM7','published'),
  ('Thanh Tuấn Homestay','stay','qb',NULL,NULL,'Bãi Đá Nhảy, Thanh Trạch.','0977536332','https://maps.app.goo.gl/TaWiRPWWvcPF9eAc6','published'),
  ('Đồi cát Quang Phú','view','qb',NULL,NULL,'567 Trương Pháp, Nam Trạch.',NULL,'https://maps.app.goo.gl/iwyMNKG5BBis85pd6','published'),
  ('Bãi biển Nhật Lệ — Đồng Hới','view','qb',17.47,106.62,NULL,NULL,'https://maps.app.goo.gl/yGMEKc8mQV533mMN7','published'),
  ('KS Thăng Long (view Nhật Lệ)','stay','qb',NULL,NULL,'View biển Nhật Lệ, gặp chị Cao Hoài Thu.','0707173173','https://maps.app.goo.gl/C4GPYpUXW3C8EuFR6','published'),
  ('Nam Long Plus Hotel','stay','qb',NULL,NULL,'28A Phan Chu Trinh, Đồng Hới.','0918923595','https://maps.app.goo.gl/TikF8fPJoNVecUiq7','published'),
  ('Nhà khách Thanh Thiếu Niên','stay','qb',NULL,NULL,NULL,'02323810447','https://maps.app.goo.gl/frn75ux8UyNQAyyBA','published'),
  ('Nhà Vườn Thuyền Trưởng','stay','qb',NULL,NULL,'Đồng Hới. Thuê nguyên căn đầy đủ tiện nghi, 2–2,5 triệu/đêm.','0847399999',NULL,'published'),
  ('An Nhiên','stay','qb',NULL,NULL,'KĐT Đông Phùng Hưng, Đồng Hới.','0827652225',NULL,'published'),
  ('Thanh Hương Motel','stay','qb',NULL,NULL,'Ngoài trung tâm Đồng Hới 3–4km, thôn 7 Bố Trạch.',NULL,'https://maps.app.goo.gl/CrVoeg5sFoBjhfmR9','published'),
  ('Nhà khách 30/4','stay','qb',NULL,NULL,'219 Trương Pháp, Đồng Hới.','0912072387','https://maps.app.goo.gl/qXhuf94uLRuaA8eA9','published'),
  ('Cơm bao cấp Quảng Bình','food','qb',NULL,NULL,NULL,'0855138222','https://maps.app.goo.gl/wsvqTeavGCHxRWz86','published'),
  ('Cơm gà đồi — Đồng Hới','food','qb',NULL,NULL,'134 Lý Thường Kiệt.',NULL,NULL,'published'),
  ('Nem lụi & bún thịt nướng — Đồng Hới','food','qb',NULL,NULL,'Nem lụi 60k/10 cái, bún thịt nướng 25k. Có ship.','0394647164',NULL,'published'),
  ('Thanh Tuấn — KS Phong Nha','stay','qb',NULL,NULL,'Khu Phong Nha còn nhiều nhà nghỉ: Carambola, Jungle Boss, Phong Nha Bolero…','0705953788',NULL,'published'),
  ('Vườn Quốc gia Phong Nha – Kẻ Bàng','view','qb',17.585,106.287,'Di sản thiên nhiên thế giới — ‘vương quốc hang động’.',NULL,NULL,'published'),
  ('Động Phong Nha','view','qb',17.586,106.288,'Đi thuyền trên sông Son vào động, sông ngầm dài nhất.',NULL,NULL,'published'),
  ('Động Thiên Đường','view','qb',17.505,106.263,'‘Hoàng cung trong lòng đất’, hang khô tráng lệ nhất châu Á.',NULL,NULL,'published'),
  ('Sông Chày – Hang Tối','view','qb',NULL,NULL,'Zipline, chèo kayak, tắm bùn khoáng.',NULL,NULL,'published'),
  ('Suối Nước Moọc','view','qb',NULL,NULL,'Suối xanh mát giữa thung lũng đá vôi, tắm suối thư giãn.',NULL,NULL,'published'),
  ('Công viên Ozo Phong Nha','view','qb',NULL,NULL,'Hệ thống trò chơi trên cây, zipline giữa rừng.',NULL,NULL,'published'),
  ('East Hill — gà nướng Phong Nha','food','qb',NULL,NULL,'Quán gà nướng chấm muối cheo nằm trên đồi, view cánh đồng Phong Nha rất đẹp, đồ ăn ngon.',NULL,NULL,'published'),
  ('Khách sạn Phương Đông — Cửa Việt','stay','qt',NULL,NULL,NULL,'0969440545',NULL,'published'),
  ('Bãi biển Trung Giang — Cửa Tùng','view','qt',17.06,107.1,'Ăn hải sản khu Trung Giang gần cầu Cửa Tùng — ngon-bổ-rẻ hơn sát bờ Cửa Việt.','0944363357','https://maps.app.goo.gl/NXRbHursAc2u3dEn7','published'),
  ('Cầu Hiền Lương — Vĩ tuyến 17','view','qt',17.0,107.0,NULL,NULL,'https://maps.app.goo.gl/uQ5D6XsuDjuis1Qt9','published'),
  ('Thành cổ Quảng Trị','view','qt',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/6fRKfYYJPZy8Nm2W7','published'),
  ('Khách sạn Song Phát — Cửa Việt','stay','qt',NULL,NULL,'Đường Hoàng Diệu.','0368136699','https://maps.app.goo.gl/T592cYRtUBLtBKDV8','published'),
  ('Eo biển xanh — Cửa Tùng','view','qt',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/21M77DhnhPGHUw5K7','published'),
  ('Địa đạo Vịnh Mốc','view','qt',NULL,NULL,'Có quán ăn ngay cổng.',NULL,'https://maps.app.goo.gl/J5pAFPGCGM59RjRj8','published'),
  ('Mũi Si','view','qt',NULL,NULL,'Hợp mọi xe, đầy đủ dịch vụ.',NULL,'https://maps.app.goo.gl/XmEQpwP3MfAX44Ep8','published'),
  ('Homestay Mũi Si','stay','qt',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/DoPjh9mszkp37DDt8','published'),
  ('Điện gió Hướng Tân','view','qt',NULL,NULL,'Hợp mọi xe, không dịch vụ.',NULL,'https://maps.app.goo.gl/UR1Gi4DbxVh2W9fm9','published'),
  ('Điện gió Liên Lập','view','qt',NULL,NULL,'Hợp mọi xe, không dịch vụ.',NULL,'https://maps.app.goo.gl/SmXDtydo8DdKzSxs9','published'),
  ('Cây cô đơn hồ Rào Quán','view','qt',NULL,NULL,'Cần xe gầm cao, không dịch vụ.',NULL,'https://maps.app.goo.gl/zM5kLramL7DS7FCY9','published'),
  ('Nghĩa trang Liệt sĩ Trường Sơn','view','qt',16.83,106.95,'Nghĩa trang liệt sĩ lớn nhất Việt Nam.',NULL,NULL,'published'),
  ('Cầu treo Đakrông','view','qt',NULL,NULL,'Cầu treo trên đường Hồ Chí Minh nhánh Tây.',NULL,NULL,'published'),
  ('Nhà nghỉ Gia Đạt','stay','hue',NULL,NULL,'58 Trần Trúc Nhẫn. Phòng đôi 4 người 500k. Cô Vân.','0906551771','https://maps.app.goo.gl/Xk6PV8iqJmBjkQo26','published'),
  ('Quán cơm chị Tẹo','food','hue',NULL,NULL,'59 Hai Bà Trưng — nhiều món Huế đặc trưng, có chỗ đỗ xe.','0905862388','https://maps.app.goo.gl/qWKw6Eiymnd3j7t67','published'),
  ('Cơm niêu Lửa Việt','food','hue',NULL,NULL,'Nội thành Huế.',NULL,'https://maps.app.goo.gl/WLZNv4XbJV1B3szx7','published'),
  ('Homestay ở Đại Nội','stay','hue',NULL,NULL,'68 Trần Nguyên Hãn, giáp phố Lê Huân. Cô Minh.','0397266119',NULL,'published'),
  ('SIMBA Homestay Huế','stay','hue',NULL,NULL,'19 Nguyễn Tuân, Vỹ Dạ.','0774446656','https://maps.app.goo.gl/sfoZqkGVZW9Xsna96','published'),
  ('KS Nữ Hoàng','stay','hue',NULL,NULL,'Nội thành Huế, ~250k/phòng đơn.','0905890455',NULL,'published'),
  ('Bull House Homestay','stay','hue',NULL,NULL,'An Cựu City.','0914050515',NULL,'published'),
  ('Bãi biển Thuận An','view','hue',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/gimRvp5nYch4LhSz5','published'),
  ('Sunshine Villa','stay','hue',NULL,NULL,'77 Thái Dương, Thuận An.','0899865931','https://maps.app.goo.gl/EmFS2aaEx7YuSRrd9','published'),
  ('Homestay Summer','stay','hue',NULL,NULL,'98 Hoàng Sa, Thuận An.','0914091418','https://maps.app.goo.gl/KxuEEuy36VR1AJPPA','published'),
  ('Cầu vượt cửa biển Thuận An','view','hue',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/GzExZJ6dLyofWoxV8','published'),
  ('Phá Tam Giang','view','hue',16.55,107.45,'Đầm phá lớn nhất Đông Nam Á, đẹp lúc hoàng hôn.','0905101060',NULL,'published'),
  ('Hiên Cát Homestay','stay','hue',NULL,NULL,'Thôn Tân Mỹ, Phong Quảng.','0388728681','https://maps.app.goo.gl/Fks9W9LNqKMNbKrW8','published'),
  ('Cầu Tư Hiền','view','hue',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/scyMugwh6fdcQFMn6','published'),
  ('Bãi biển Cảnh Dương — Chân Mây','view','hue',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/iaMTeSbNABE71x3X8','published'),
  ('Nhà nghỉ Cảnh Dương','stay','hue',NULL,NULL,'Chân Mây – Lăng Cô.','0935110905','https://maps.app.goo.gl/QbPurAahDeLdderT6','published'),
  ('Nhà nghỉ Hoàng Ngọc — biển Cảnh Dương','stay','hue',NULL,NULL,NULL,'0935106990','https://maps.app.goo.gl/uKNt6B8ZAoxm5zp89','published'),
  ('Bãi biển Tân Cảnh Dương','view','hue',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/uPM2eVWQrVGCUsoh7','published'),
  ('Bãi biển Chân Mây','view','hue',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/RZJiwXwxxtdb3ZuG6','published'),
  ('Nhà nghỉ Nguyệt Ánh','stay','hue',NULL,NULL,'Biển Cảnh Dương, Chân Mây.','0978941527','https://maps.app.goo.gl/BSktNKbee9YRh9To7','published'),
  ('Nhà nghỉ Anh Dũng','stay','hue',NULL,NULL,'Cảnh Dương, Chân Mây.','0899081701','https://maps.app.goo.gl/gHuBnsTyCNHcia2W6','published'),
  ('Bình An Guest House','stay','hue',NULL,NULL,'Thôn Bình An, Chân Mây.','0935000727','https://maps.app.goo.gl/iq1e4hZCVhqNCCxD7','published'),
  ('MIMI Guest House','stay','hue',NULL,NULL,'Lộc Vĩnh, Chân Mây.','0774552912','https://maps.app.goo.gl/NehDvWUe9oiX9AGPA','published'),
  ('Ghềnh Chân Mây','view','hue',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/bbKhNRT4LeDTfxJ2A','published'),
  ('Điểm ngắm bình minh Bãi Bàng — Chân Mây','view','hue',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/gKehTFJybF24tCBx6','published'),
  ('Bãi biển Lăng Cô','view','hue',16.23,108.08,'Ăn bên bãi biển, đừng ăn bên đầm (đắt mà không ngon bằng).',NULL,'https://maps.app.goo.gl/K4JCVvp9TNumQnNe9','published'),
  ('Muối Villa Lăng Cô','stay','hue',NULL,NULL,NULL,'0937460888','https://maps.app.goo.gl/6B8Zr9CNSBdYfx9U8','published'),
  ('Nhà nghỉ dưỡng Lăng Cô — Bộ Công An','stay','hue',NULL,NULL,'Đ. Lạc Long Quân.','02343683890','https://maps.app.goo.gl/6oS5yAZ67D8H5EXg8','published'),
  ('Vitamin Sea Home','stay','hue',NULL,NULL,'Lăng Cô.','0974136886','https://maps.app.goo.gl/3NCkeNQ8WVvhvroAA','published'),
  ('Khu nghỉ dưỡng Lăng Cô T26','stay','hue',NULL,NULL,'493 Lạc Long Quân.','0935483548','https://maps.app.goo.gl/F7nHorZ8Us8KXBS79','published'),
  ('Hải Vân Quan','view','hue',16.2,108.13,'Thiên hạ đệ nhất hùng quan, đỉnh đèo Hải Vân.',NULL,'https://maps.app.goo.gl/oZyCKhBQ4atjz2kk8','published'),
  ('Đại Nội Huế (Kinh thành)','view','hue',16.469,107.578,'Quần thể di tích cố đô triều Nguyễn, di sản UNESCO.',NULL,NULL,'published'),
  ('Chùa Thiên Mụ','view','hue',16.4533,107.5547,'Biểu tượng Huế bên sông Hương, tháp Phước Duyên 7 tầng.',NULL,NULL,'published'),
  ('Lăng Khải Định','view','hue',16.401,107.581,'Kiến trúc Đông–Tây, khảm sành sứ tinh xảo.',NULL,NULL,'published'),
  ('Lăng Tự Đức','view','hue',16.457,107.552,'Lăng thơ mộng, hồ nước cây xanh, kiến trúc hài hòa thiên nhiên.',NULL,NULL,'published'),
  ('Lăng Minh Mạng','view','hue',16.417,107.553,'Bố cục đối xứng uy nghiêm bên ngã ba sông.',NULL,NULL,'published'),
  ('Cầu Trường Tiền','view','hue',16.4684,107.592,'Biểu tượng Huế bắc qua sông Hương.',NULL,NULL,'published'),
  ('Chợ Đông Ba','view','hue',16.4717,107.587,'Chợ lớn nhất Huế — đặc sản & quà lưu niệm.',NULL,NULL,'published'),
  ('Bãi tắm Mân Thái','view','dn',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/jLXZTPSmkRDv9Fff7','published'),
  ('Ngũ Hành Sơn','view','dn',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/C9hVShNNi2RorRZU9','published'),
  ('Bãi biển Mỹ Khê','view','dn',16.06,108.25,NULL,NULL,NULL,'published'),
  ('Bãi biển An Bàng — Hội An','view','dn',15.9,108.32,NULL,NULL,'https://maps.app.goo.gl/fHVdfWANZF7YYGML6','published'),
  ('An Bang Seascape Homestay','stay','dn',NULL,NULL,'82 Nguyễn Phan Vinh, Hội An.','0904885502','https://maps.app.goo.gl/5G1LM3UKFYemiXJv6','published'),
  ('Bãi biển Cửa Đại','view','dn',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/6oSnpNBXwh3paz1t8','published'),
  ('Bãi tắm Cửa Đại','view','dn',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/8pimYUoxunkpERcWA','published'),
  ('Làng bích hoạ Tam Thanh','view','dn',15.47,108.62,NULL,NULL,'https://maps.app.goo.gl/sZAv9mRcrZnAyxJu8','published'),
  ('Homestay Rio''s Gió Biển — Làng Bích Họa','stay','dn',NULL,NULL,NULL,'0935199159','https://maps.app.goo.gl/r6FMNGqwjGkVdwoe9','published'),
  ('Homestay Ngọc Lan','stay','dn',NULL,NULL,'Thôn Hòa Hạ, Quảng Phú.','0868655433','https://maps.app.goo.gl/JgTe7yi27yrNgxea8','published'),
  ('Mi Casa Garden','stay','dn',NULL,NULL,'Thanh Niên, Quảng Phú.','0902158919','https://maps.app.goo.gl/zLdfVr82h2x3ovHS7','published'),
  ('Homestay Hoa Giấy','stay','dn',NULL,NULL,'Đường Thanh Niên, Quảng Phú.','0914747266','https://maps.app.goo.gl/auoK3CfF2ioHZUNKA','published'),
  ('Tam Tien Homes','stay','dn',NULL,NULL,'Homestay duy nhất có bãi cát dài đi thẳng xuống biển, không bị che chắn.','0901998115','https://maps.app.goo.gl/hnBdvgyGv37uMgJs9','published'),
  ('Chợ cá Tam Tiến','food','dn',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/YGaQg3z3gYuphDrG6','published'),
  ('Bà Nà Hills','view','dn',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/j26WFCoNfGeDg27o9','published'),
  ('Nhà nghỉ Việt Thương','stay','dn',NULL,NULL,'Hòa Tiến.','0362955674','https://maps.app.goo.gl/xBmuJQXwrAkK2uqB8','published'),
  ('Bean''s House Riverfront','stay','dn',NULL,NULL,'285 Trần Hưng Đạo, An Hải.','0777930210','https://maps.app.goo.gl/MJaWPSGAkvjE1nTn9','published'),
  ('Khách sạn MT Ngô Quyền — Sơn Trà','stay','dn',NULL,NULL,'Sát trạm sạc VinFast, bãi đỗ ô tô rộng, thuê xe AB 100k/ngày, giá từ 300k.','0367772088','https://maps.app.goo.gl/pomzP4jkZTZADSGe7','published'),
  ('Homestay biển Làng Bích Hoạ — Tam Kỳ','stay','dn',NULL,NULL,NULL,'0387091611','https://maps.app.goo.gl/ENsDWGUXABBvz8AY9','published'),
  ('KS Phi Hùng','stay','dn',NULL,NULL,'Hùng Vương.',NULL,'https://maps.app.goo.gl/Qg5EAZfcKys2C4b67','published'),
  ('KS ở Non Nước','stay','dn',NULL,NULL,'65 Võ Duy Ninh, Sơn Trà. Studio bếp riêng ~299k, gần biển Mân Thái, có chỗ đỗ ô tô.','0934568077',NULL,'published'),
  ('Homestay Snow Pearl','stay','dn',NULL,NULL,'10 Trần Cao Vân, gần phố cổ, ~300k.','0905434943','https://maps.app.goo.gl/LV1JnsMXhcFhjqBT9','published'),
  ('Phố cổ Hội An (Chùa Cầu)','view','dn',15.877,108.327,'Di sản UNESCO, phố đèn lồng, Chùa Cầu 400 năm.',NULL,NULL,'published'),
  ('Thánh địa Mỹ Sơn','view','dn',15.764,108.124,'Di sản UNESCO — quần thể đền tháp Chăm Pa.',NULL,NULL,'published'),
  ('Cù Lao Chàm','view','dn',NULL,NULL,'Cụm 8 đảo, lặn ngắm san hô; đi tàu/cano từ Cửa Đại.',NULL,NULL,'published'),
  ('Cầu Rồng','view','dn',16.061,108.227,'Biểu tượng Đà Nẵng, phun lửa & nước tối T7–CN.',NULL,NULL,'published'),
  ('Chùa Linh Ứng – Bán đảo Sơn Trà','view','dn',16.1003,108.2787,'Tượng Quan Âm cao 67m hướng ra biển.',NULL,NULL,'published'),
  ('Đỉnh Bàn Cờ – Sơn Trà','view','dn',16.115,108.296,'Đỉnh cao nhất bán đảo, view toàn cảnh Đà Nẵng.',NULL,NULL,'published'),
  ('Bảo tàng Điêu khắc Chăm','view','dn',16.0604,108.223,'Bộ sưu tập cổ vật Chăm Pa lớn nhất Việt Nam.',NULL,NULL,'published'),
  ('Rạn Nam Ô','view','dn',NULL,NULL,'Rạn đá phủ rêu xanh dưới chân đèo Hải Vân, vào miễn phí.',NULL,NULL,'published'),
  ('Bãi tắm Sa Huỳnh','view','qng',14.68,109.05,'Bãi biển vắng, cát đẹp trên đường vào Bình Định.',NULL,NULL,'published'),
  ('Chùa Minh Đức','view','qng',NULL,NULL,'Trên cung đường ven biển Quảng Ngãi.',NULL,NULL,'published'),
  ('Đảo Lý Sơn','view','qng',NULL,NULL,'Đi tàu ra, dịch vụ cơ bản.',NULL,'https://maps.app.goo.gl/bxKUN5k8VxQULEf38','published'),
  ('Mũi Ba Làng An','view','qng',NULL,NULL,'Mũi đá đen, hải đăng, view biển hoang sơ.',NULL,NULL,'published'),
  ('Biển Mỹ Khê (Quảng Ngãi)','view','qng',NULL,NULL,'Bãi biển dài, cát trắng mịn, vắng.',NULL,NULL,'published'),
  ('Bãi biển Tam Quan Bắc','view','bd',NULL,NULL,'Đường tỉnh 639, dừng nghỉ trưa có bãi tắm đẹp & quán ăn.',NULL,NULL,'published'),
  ('Bến Lộ Diêu — Tàu Không Số','view','bd',NULL,NULL,'Đường tỉnh 639.',NULL,NULL,'published'),
  ('Cầu Đề Gi','view','bd',NULL,NULL,NULL,NULL,NULL,'published'),
  ('Eo Gió — Nhơn Lý','view','bd',13.82,109.34,'Cung biển đẹp nhất Quy Nhơn. Mua vé vào tản bộ ngắm biển Đông.',NULL,NULL,'published'),
  ('Bãi biển Quy Nhơn','view','bd',13.77,109.23,'Hải sản dọc Xuân Diệu & Ngọc Hân Công Chúa.',NULL,NULL,'published'),
  ('Hòn Khô — Làng Chài Nhơn Hải','view','bd',NULL,NULL,'Lặn ngắm san hô, chèo SUP. Gửi xe, mua vé tàu ra đảo ~5 phút.',NULL,NULL,'published'),
  ('Bãi Kỳ Co','view','bd',NULL,NULL,'Leo núi vào bãi (có vé) hoặc đi thuyền từ Nhơn Lý. Thuê phao/kính/đồ bơi tại bãi.',NULL,NULL,'published'),
  ('Tháp Đôi Chămpa','view','bd',NULL,NULL,'Phố Trần Hưng Đạo, di tích Chăm giữa thành phố.',NULL,NULL,'published'),
  ('Ghềnh Ráng Tiên Sa','view','bd',NULL,NULL,'Khu di tích nhà thơ Hàn Mặc Tử.',NULL,NULL,'published'),
  ('Quán Vị Cua — bún Rạm','food','bd',NULL,NULL,'02 Ngọc Hân Công Chúa, đặc sản bún rạm.',NULL,NULL,'published'),
  ('Lẩu sứa Thanh Kiều','food','bd',NULL,NULL,'69/1 Trần Hưng Đạo — gỏi cá & lẩu sứa đặc sản Quy Nhơn.',NULL,NULL,'published'),
  ('Lẩu sứa Hoa Hoa','food','bd',NULL,NULL,'8 Nguyễn Dữ, Hải Cảng.',NULL,NULL,'published'),
  ('Hệ thống Ông Minh (bò tơ, hải sản)','food','bd',NULL,NULL,'Nguyễn Trung Tín, Nguyễn Thị Định, Bùi Hữu Nghĩa.',NULL,NULL,'published'),
  ('Quán nhậu Biển Hồ — Quy Nhơn','food','bd',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/rrLPzB3xMg6rJr2Q9','published'),
  ('TMS Sea View Quy Nhơn','stay','bd',NULL,NULL,NULL,'0966377719',NULL,'published'),
  ('Luxury Apartment Altara','stay','bd',NULL,NULL,'76 Trần Hưng Đạo. Căn 2 ngủ 1 khách, đầy đủ tiện nghi, hơn 600k/đêm.','0796719039',NULL,'published'),
  ('Xavia Hotel','stay','bd',NULL,NULL,'Trung tâm Quy Nhơn.','0941351557',NULL,'published'),
  ('KS Hà Min','stay','bd',NULL,NULL,'Trung tâm Quy Nhơn.','0913600327',NULL,'published'),
  ('KS Dezon','stay','bd',NULL,NULL,'Trung tâm Quy Nhơn.','0983809679',NULL,'published'),
  ('Gallery Home','stay','bd',NULL,NULL,'Trung tâm Quy Nhơn.','0913595012',NULL,'published'),
  ('Le Mint Hotel','stay','bd',NULL,NULL,'Trung tâm Quy Nhơn — được khen ổn.','025636866889',NULL,'published'),
  ('Hotel Bel-air','stay','bd',NULL,NULL,'Trung tâm Quy Nhơn.','0942251779',NULL,'published'),
  ('KS Ciao','stay','bd',NULL,NULL,NULL,'02566516688',NULL,'published'),
  ('Ngọc Linh Hotel','stay','bd',NULL,NULL,NULL,'02563546699',NULL,'published'),
  ('Yến Vi Hotel','stay','bd',NULL,NULL,NULL,'02566294234',NULL,'published'),
  ('Money Fine Hotel','stay','bd',NULL,NULL,NULL,'0906507647',NULL,'published'),
  ('KS Anh Vy','stay','bd',NULL,NULL,NULL,'02563847763',NULL,'published'),
  ('KS Hoàng Hưng','stay','bd',NULL,NULL,'Khu quảng trường.','0905410628',NULL,'published'),
  ('Seaside Hotel','stay','bd',NULL,NULL,'Khu quảng trường.','0903954915',NULL,'published'),
  ('Mio Hotel','stay','bd',NULL,NULL,'Khu quảng trường.','0256247879',NULL,'published'),
  ('An House','stay','bd',NULL,NULL,'Khu quảng trường.','02563629369',NULL,'published'),
  ('À Ơi Home','stay','bd',NULL,NULL,'Khu TP/Bãi Xếp.','0357035590','https://maps.app.goo.gl/a7DXpBf5VCuejgH77','published'),
  ('Nắng Home','stay','bd',NULL,NULL,'Khu TP/Bãi Xếp.','0328865768',NULL,'published'),
  ('Sen Trúc Home','stay','bd',NULL,NULL,'Khu TP/Bãi Xếp.','0962071917',NULL,'published'),
  ('BBnB Home Quy Nhơn','stay','bd',NULL,NULL,NULL,'0902420408',NULL,'published'),
  ('Home Bảo Bảo','stay','bd',NULL,NULL,NULL,'0914299177',NULL,'published'),
  ('Home Sunrise','stay','bd',NULL,NULL,NULL,'02563535151',NULL,'published'),
  ('Pimira Home','stay','bd',NULL,NULL,NULL,'0908503239',NULL,'published'),
  ('Home Sóng Coffee','stay','bd',NULL,NULL,'Hòn Khô – Nhơn Hải.','0846065545',NULL,'published'),
  ('Sea House Home','stay','bd',NULL,NULL,'Hòn Khô – Nhơn Hải.','0389901821',NULL,'published'),
  ('Cá Home','stay','bd',NULL,NULL,'Hòn Khô – Nhơn Hải.','0933677764',NULL,'published'),
  ('Phát Lợi Hotel','stay','bd',NULL,NULL,'Hòn Khô – Nhơn Hải.','0369727455',NULL,'published'),
  ('Viad Nhơn Hải Home','stay','bd',NULL,NULL,NULL,'0985899698',NULL,'published'),
  ('Nhơn Hải Beach Hotel','stay','bd',NULL,NULL,NULL,'0373358858',NULL,'published'),
  ('FLC Luxury Resort','stay','bd',NULL,NULL,'Eo Gió – Nhơn Lý.','02566288888',NULL,'published'),
  ('Casa de Miramar','stay','bd',NULL,NULL,'Eo Gió – Nhơn Lý.','0944941999',NULL,'published'),
  ('Happiness Hotel','stay','bd',NULL,NULL,'Eo Gió – Nhơn Lý.','02563845845',NULL,'published'),
  ('Ngõ Coffee Home','stay','bd',NULL,NULL,'Eo Gió – Nhơn Lý.','0901111799',NULL,'published'),
  ('LYS Hotel','stay','bd',NULL,NULL,'Eo Gió – Nhơn Lý.','0905042699',NULL,'published'),
  ('Mộc Sỏi Home & Mộc Núi Home','stay','bd',NULL,NULL,'Eo Gió – Nhơn Lý (cùng chủ).','0888046866',NULL,'published'),
  ('Chài Village Hotel','stay','bd',NULL,NULL,NULL,'0988146777',NULL,'published'),
  ('Home Vũng Nồm','stay','bd',NULL,NULL,NULL,'0989976339',NULL,'published'),
  ('Home Sao Biển','stay','bd',NULL,NULL,'Khu Trung Lương.','0393060764',NULL,'published'),
  ('Biển Nhớ Home','stay','bd',NULL,NULL,'Khu Trung Lương.','0986455125',NULL,'published'),
  ('Hom Nhà Của Ba','stay','bd',NULL,NULL,'Khu Trung Lương.','0988227267',NULL,'published'),
  ('Má Năm Home','stay','bd',NULL,NULL,'Khu Trung Lương.','0981401837',NULL,'published'),
  ('Cá Mặn Home','stay','bd',NULL,NULL,'Khu Trung Lương.','0932356214',NULL,'published'),
  ('Nhà Ba Cơm Má Home','stay','bd',NULL,NULL,'Khu Trung Lương.','0977001849',NULL,'published'),
  ('Biển Tình Home','stay','bd',NULL,NULL,'Khu Trung Lương — có thể dậy sớm ra bãi mua hải sản tươi về tự chế biến hoặc nhờ quản gia nấu.','0982850092',NULL,'published'),
  ('Home Lườiii','stay','bd',NULL,NULL,'Khu Mỹ Thắng, Phù Mỹ.','0916359965',NULL,'published'),
  ('Tổ Ong Kiến','stay','bd',NULL,NULL,'Khu Mỹ Thắng, Phù Mỹ.','0902157730',NULL,'published'),
  ('Tháp Bánh Ít','view','bd',13.878,109.113,'Cụm tháp Chăm trên đồi, thế kỷ XI.',NULL,NULL,'published'),
  ('Bảo tàng Quang Trung','view','bd',13.879,108.932,'Tưởng niệm vua Quang Trung & võ Tây Sơn (sâu trong đất liền).',NULL,NULL,'published'),
  ('Bãi biển Xuân Hải','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/6dQMoWDTwJRtbEec8','published'),
  ('Bãi biển Bãi Nồm','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/YZZTErccEYFBtVoK8','published'),
  ('Bãi biển Vịnh Hòa','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/XkJzFX69nLDh35hy9','published'),
  ('Bãi biển Từ Nham','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/qXQAUm7ZvaCe3nwA7','published'),
  ('Biển Gành Đỏ','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/QFXTTV3AZH6Q7U7a6','published'),
  ('Bãi biển Gành Đỏ','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/bLvpABTZTm73tLi78','published'),
  ('Hải đăng Gành Đèn','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/Rtw6HenbSn6J7K8w5','published'),
  ('Gành Đá Đĩa','view','py',13.28,109.28,'Cột đá bazan xếp tổ ong độc nhất.',NULL,'https://maps.app.goo.gl/oyeVD5gP7fWzft2z5','published'),
  ('Cảng cá Phú Lương','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/Z3s76PgpwFUJeYKg6','published'),
  ('Bãi tắm Làng Chài','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/TGfzu1KUkNoXuGe19','published'),
  ('Gành Ông','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/K6zB2vXzZQ5p5LVKA','published'),
  ('Bãi biển Long Thủy','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/6Hdh9KCyxoQPkM139','published'),
  ('Bãi biển Tuy Hòa','view','py',13.08,109.32,NULL,NULL,'https://maps.app.goo.gl/DH3Mo36ZRRENhDDDA','published'),
  ('Tháp Nghinh Phong — Tuy Hòa','view','py',13.08,109.33,NULL,NULL,NULL,'published'),
  ('Làng Lò — Phú Yên','view','py',NULL,NULL,'Hòa Hiệp.',NULL,'https://maps.app.goo.gl/uv8XpE7tPYJXZaZg7','published'),
  ('Làng Biển Homestay Phú Yên','stay','py',NULL,NULL,'Hòa Hiệp.','0792305305','https://maps.app.goo.gl/LPPTnEX29ApnV8TE7','published'),
  ('Hotel Anh Quốc','stay','py',NULL,NULL,'Đường Lê Hanh, Hòa Hiệp.','0365555957','https://maps.app.goo.gl/QYFqYTGnZV7xHM6U7','published'),
  ('SandA Villa','stay','py',NULL,NULL,'KP Phú Thọ, Hòa Hiệp.','0939406479','https://maps.app.goo.gl/wuBgS7MyDRiNNALz8','published'),
  ('Phú Yên Bluesea Villas','stay','py',NULL,NULL,'Trần Phú, Hòa Hiệp. Có bể bơi.','0913018882','https://maps.app.goo.gl/mArmRAa93mGDQUpg6','published'),
  ('Nhà nghỉ An Phát','stay','py',NULL,NULL,'Phú Thọ, Hòa Hiệp. Phòng đơn 300k.','0987379770','https://maps.app.goo.gl/1vH8rKYGuUcaEv6A8','published'),
  ('Homestay Ông Bà Tám Làng Lò','stay','py',NULL,NULL,'Biển Lò 3, KP Phú Thọ 3, Hòa Hiệp.','0918861934','https://maps.app.goo.gl/DmL8zKwxGXXyupot5','published'),
  ('Homestay Đất Phú','stay','py',NULL,NULL,'KP Đa Ngư, Hòa Hiệp.','0935359957','https://maps.app.goo.gl/BtXWMuGRtJR46xTVA','published'),
  ('Làng Chài Homestay Phú Yên','stay','py',NULL,NULL,NULL,'0976983336','https://maps.app.goo.gl/GtfiPvENs2DtuJyf8','published'),
  ('Gành đá Bãi Gốc','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/6nSgH5V7aC5MgtH36','published'),
  ('Cung đường biển đẹp nhất Phú Yên','view','py',NULL,NULL,'QL29, Hòa Xuân.',NULL,'https://maps.app.goo.gl/bxLCtwuDZcoSWFrY6','published'),
  ('Viewpoint đường ven biển Phú Yên','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/h6YV1EciPkFfkZVz7','published'),
  ('Bãi biển Bãi Môn — Mũi Điện','view','py',12.88,109.45,'Điểm đón bình minh đầu tiên trên đất liền Việt Nam.',NULL,'https://maps.app.goo.gl/mPW9NNouwxZxKQzs7','published'),
  ('Khu di tích Bến Tàu Không Số Vũng Rô','view','py',12.87,109.4,NULL,NULL,'https://maps.app.goo.gl/CrVZ5iJY3LNWJvqK8','published'),
  ('Điểm check-in địa phận Phú Yên – Khánh Hòa','view','py',NULL,NULL,NULL,NULL,'https://maps.app.goo.gl/cKxsMeiowZ4ZZh3i9','published'),
  ('Tháp Nhạn','view','py',13.0883,109.305,'Tháp Chăm ~800 tuổi, biểu tượng Tuy Hòa, ngắm hoàng hôn.',NULL,NULL,'published'),
  ('Bãi Xép','view','py',13.135,109.297,'Phim trường ‘Tôi thấy hoa vàng trên cỏ xanh’.',NULL,NULL,'published'),
  ('Nhà thờ Mằng Lăng','view','py',13.405,109.275,'Nhà thờ Gothic cổ, lưu cuốn sách quốc ngữ in đầu tiên.',NULL,NULL,'published'),
  ('Hòn Yến','view','py',13.317,109.293,'Danh thắng quốc gia, rạn san hô lộ khi triều rút.',NULL,NULL,'published'),
  ('Đầm Ô Loan','view','py',13.28,109.28,'Đầm nước lợ, đặc sản sò huyết.',NULL,NULL,'published'),
  ('Cầu gỗ Ông Cọp','view','py',13.37,109.28,'Cầu gỗ dài bắc qua sông, lối tắt tới Gành Đá Đĩa.',NULL,NULL,'published'),
  ('Bãi rêu Xóm Rớ','view','py',NULL,NULL,'Kè đá phủ rêu xanh khi triều rút, Tuy Hòa.',NULL,NULL,'published'),
  ('Vịnh Xuân Đài','view','py',NULL,NULL,'Vịnh biển đẹp ở Sông Cầu, nhiều hải sản.',NULL,NULL,'published'),
  ('VinWonders Hòn Tre','view','kh',12.2103,109.244,'Công viên giải trí + cáp treo vượt biển 3,3km.',NULL,NULL,'published'),
  ('Hòn Mun','view','kh',12.165,109.295,'Khu bảo tồn biển, lặn ngắm san hô rực rỡ.',NULL,NULL,'published'),
  ('Hòn Tằm','view','kh',12.18,109.27,'Đảo bãi đẹp, tắm bùn khoáng, thể thao biển.',NULL,NULL,'published'),
  ('Hòn Một','view','kh',12.17,109.285,'Đảo nhỏ, san hô lộ thiên, lặn biển.',NULL,NULL,'published'),
  ('Tháp Bà Ponagar','view','kh',12.2655,109.1955,'Cụm tháp Chăm cổ hơn 1.200 năm, 61 Hai Tháng Tư.',NULL,NULL,'published'),
  ('Chùa Long Sơn','view','kh',12.2545,109.181,'Chùa cổ dưới núi Trại Thủy, tượng Phật trắng.',NULL,NULL,'published'),
  ('Nhà thờ Núi (Nhà thờ Đá)','view','kh',12.2455,109.1865,'Nhà thờ đá kiến trúc Gothic giữa phố.',NULL,NULL,'published'),
  ('Viện Hải dương học','view','kh',12.2055,109.216,'Thủy cung trưng bày hàng trăm loài biển.',NULL,NULL,'published'),
  ('Hòn Chồng','view','kh',12.268,109.208,'Bãi đá hình khối kỳ lạ, ngắm vịnh.',NULL,NULL,'published'),
  ('Bãi biển Trần Phú','view','kh',12.235,109.196,'Bờ cát trắng ~7km giữa thành phố.',NULL,NULL,'published'),
  ('Tháp Trầm Hương','view','kh',12.2375,109.1955,'Tháp hình búp sen ở quảng trường 2/4.',NULL,NULL,'published'),
  ('Đảo Điệp Sơn','view','kh',12.62,109.3,'Con đường cát giữa biển, vịnh Vân Phong.',NULL,NULL,'published'),
  ('Đảo Yến – Hòn Nội','view','kh',12.16,109.33,'‘Bãi tắm đôi’, đảo yến hoang sơ.',NULL,NULL,'published'),
  ('Suối khoáng nóng Tháp Bà / I-Resort','view','kh',12.27,109.18,'Tắm bùn khoáng nóng nổi tiếng.',NULL,NULL,'published'),
  ('Dốc Lết','view','kh',12.46,109.215,'Bãi cát trắng dài + đồi cát (Ninh Hòa).',NULL,NULL,'published'),
  ('Bãi Dài Cam Ranh','view','kh',11.98,109.21,'Bãi biển cát trắng dài, nước trong (Cam Ranh).',NULL,NULL,'published'),
  ('Đảo Bình Hưng','view','kh',11.43,109.21,'Đảo tôm hùm, bè nổi, lặn biển (Cam Ranh).',NULL,NULL,'published'),
  ('Khu du lịch Ba Hồ','view','kh',NULL,NULL,'Suối thác 3 hồ giữa rừng (Ninh Hòa).',NULL,NULL,'published'),
  ('Bún cá Nguyên Loan','food','kh',NULL,NULL,'123 Ngô Gia Tự — bún cá/sứa gần 45 năm.',NULL,NULL,'published'),
  ('Nem nướng Đặng Văn Quyên','food','kh',NULL,NULL,'Hàn Thuyên/Lãn Ông — nem nướng Ninh Hòa.',NULL,NULL,'published'),
  ('Bò nướng Lạc Cảnh','food','kh',NULL,NULL,'44 Nguyễn Bỉnh Khiêm — bò nướng đặc sản.',NULL,NULL,'published'),
  ('Bún sứa Năm Beo','food','kh',NULL,NULL,'B2 chung cư Phan Bội Châu — bún cá sứa nước trong.',NULL,NULL,'published'),
  ('Bánh căn 134 Trần Quý Cáp','food','kh',NULL,NULL,'Bánh căn nhân mực/trứng nổi tiếng.',NULL,NULL,'published'),
  ('Vịnh Vĩnh Hy','view','nt',11.71,109.18,'Một trong những vịnh đẹp nhất VN, tàu đáy kính, san hô.',NULL,NULL,'published'),
  ('Hang Rái','view','nt',11.65,109.16,'Ghềnh đá cổ, ‘thác trên biển’, săn ảnh bình minh.',NULL,NULL,'published'),
  ('Đồi cát Nam Cương','view','nt',11.52,108.98,'Tiểu sa mạc, check-in cồn cát.',NULL,NULL,'published'),
  ('Biển Ninh Chữ','view','nt',11.58,109.03,'Bãi biển đẹp, chợ cá, ngắm hoàng hôn.',NULL,NULL,'published'),
  ('Tháp Po Klong Garai','view','nt',11.59,108.96,'Cụm tháp Chăm gạch đỏ nguyên vẹn nhất VN, đồi Trầu.',NULL,NULL,'published'),
  ('Vườn nho Thái An','view','nt',11.68,109.14,'Thủ phủ nho, hái nho tại vườn (đường ra Vĩnh Hy).',NULL,NULL,'published'),
  ('Mũi Dinh','view','nt',11.36,109.03,'Hải đăng cổ 1904, bãi biển hoang sơ, đồi cát.',NULL,NULL,'published'),
  ('Làng gốm Bàu Trúc','view','nt',11.55,108.92,'Làng gốm cổ nhất Đông Nam Á (UNESCO).',NULL,NULL,'published'),
  ('VQG Núi Chúa','view','nt',11.72,109.13,'Khu dự trữ sinh quyển, trekking, cắm trại.',NULL,NULL,'published'),
  ('Đồng cừu An Hòa','view','nt',NULL,NULL,'Cánh đồng chăn thả cừu nổi tiếng, chụp ảnh.',NULL,NULL,'published'),
  ('Biển Cà Ná','view','nt',NULL,NULL,'Bãi biển hoang sơ phía nam, đá xếp chênh vênh.',NULL,NULL,'published'),
  ('Cừu – dê nướng Phan Rang','food','nt',NULL,NULL,'Đặc sản cừu nướng, dê xào lăn.',NULL,NULL,'published'),
  ('Bánh căn Phan Rang','food','nt',NULL,NULL,'Bánh căn chấm nước cá kho/mắm nêm.',NULL,NULL,'published'),
  ('Gỏi cá mai','food','nt',NULL,NULL,'Cá mai cuốn bánh tráng, chấm nước đậu phộng.',NULL,NULL,'published'),
  ('Đồi Cát Bay Mũi Né','view','bt',10.94,108.29,'Cồn cát đổi hình theo gió, trượt cát, hoàng hôn.',NULL,NULL,'published'),
  ('Bàu Trắng','view','bt',11.05,108.41,'Đồi cát trắng + hồ sen, ‘tiểu sa mạc’, đi jeep.',NULL,NULL,'published'),
  ('Suối Tiên Mũi Né','view','bt',10.95,108.27,'Suối nước đỏ uốn lượn giữa vách cát.',NULL,NULL,'published'),
  ('Hòn Rơm','view','bt',10.97,108.34,'Bãi tắm hoang sơ + làng chài.',NULL,NULL,'published'),
  ('Bãi đá Ông Địa','view','bt',10.94,108.18,'Bãi đá + tượng Ông Địa ven biển.',NULL,NULL,'published'),
  ('Tháp Po Sah Inư','view','bt',10.94,108.13,'Tháp Chăm cổ trên đồi Bà Nài, gần Phan Thiết.',NULL,NULL,'published'),
  ('Lầu Ông Hoàng','view','bt',10.94,108.14,'Di tích + view biển, gắn thơ Hàn Mặc Tử.',NULL,NULL,'published'),
  ('Làng chài Mũi Né','view','bt',10.93,108.29,'Làng chài, chợ hải sản buổi sáng.',NULL,NULL,'published'),
  ('Trường Dục Thanh','view','bt',10.928,108.098,'Trường xưa nơi Bác Hồ từng dạy học.',NULL,NULL,'published'),
  ('Bãi đá Cổ Thạch – Chùa Hang','view','bt',11.43,108.84,'Bãi đá bảy màu + chùa trong hang (Tuy Phong).',NULL,NULL,'published'),
  ('Lẩu thả Phan Thiết','food','bt',NULL,NULL,'Đặc sản bày hình bông sen, cá suốt + bún.',NULL,NULL,'published'),
  ('Bánh căn Lân Nguyệt','food','bt',NULL,NULL,'8 Hải Thượng Lãn Ông — bánh căn chấm xíu mại.',NULL,NULL,'published'),
  ('Bánh quai vạc','food','bt',NULL,NULL,'152 Võ Thị Sáu — bánh quai vạc tôm.',NULL,NULL,'published'),
  ('Răng mực nướng','food','bt',NULL,NULL,'Món đường phố nướng giòn cay.',NULL,NULL,'published'),
  ('Hải sản Bi Bo','food','bt',NULL,NULL,'191 Nguyễn Đình Chiểu, Mũi Né — hải sản bình dân.',NULL,NULL,'published'),
  ('Bánh xèo Phan Thiết','food','bt',NULL,NULL,'Bánh xèo tôm mực, ăn cuốn rau.',NULL,NULL,'published'),
  ('Mì Quảng vịt','food','bt',NULL,NULL,'129 Trần Phú — mì Quảng vịt Phan Thiết.',NULL,NULL,'published'),
  ('Tượng Chúa Kitô Vua','view','vt',10.3375,107.0865,'Tượng Chúa 32m trên Núi Nhỏ, leo lên ngắm toàn cảnh.',NULL,NULL,'published'),
  ('Hải đăng Vũng Tàu','view','vt',10.342,107.0855,'Hải đăng cổ nhất VN (1862) trên Núi Nhỏ.',NULL,NULL,'published'),
  ('Mũi Nghinh Phong','view','vt',10.33,107.085,'Mũi đá + ‘Cổng Trời’, check-in gió biển.',NULL,NULL,'published'),
  ('Bãi Sau (Thùy Vân)','view','vt',10.348,107.103,'Bãi tắm dài, sôi động, nhiều dịch vụ.',NULL,NULL,'published'),
  ('Bãi Trước','view','vt',10.35,107.075,'Bãi biển trung tâm, hàng dừa, ngắm hoàng hôn.',NULL,NULL,'published'),
  ('Bạch Dinh','view','vt',10.353,107.073,'Biệt thự Pháp cổ trên sườn Núi Lớn, bảo tàng.',NULL,NULL,'published'),
  ('Niết Bàn Tịnh Xá','view','vt',10.345,107.078,'Chùa đẹp bên sườn Núi Nhỏ, hướng biển.',NULL,NULL,'published'),
  ('Thích Ca Phật Đài','view','vt',10.358,107.078,'Tượng Phật ngồi thiền trên đài sen.',NULL,NULL,'published'),
  ('Khu du lịch Hồ Mây','view','vt',10.35,107.08,'Công viên trên Núi Lớn, cáp treo, hồ.',NULL,NULL,'published'),
  ('Đồi Con Heo','view','vt',10.337,107.09,'Đồi cỏ + xích đu view biển, check-in.',NULL,NULL,'published'),
  ('Biển Long Hải','view','vt',10.39,107.22,'Bãi biển yên bình ngoài trung tâm.',NULL,NULL,'published'),
  ('Hồ Đá Xanh','view','vt',NULL,NULL,'Hồ nước xanh ngọc giữa núi đá (Tân Thành).',NULL,NULL,'published'),
  ('Hồ Tràm','view','vt',NULL,NULL,'Biển hoang sơ, resort, casino (Xuyên Mộc).',NULL,NULL,'published'),
  ('Suối nước nóng Bình Châu','view','vt',NULL,NULL,'Suối khoáng nóng giữa rừng (Xuyên Mộc).',NULL,NULL,'published'),
  ('Núi Minh Đạm','view','vt',NULL,NULL,'Căn cứ cách mạng, hang động, view biển (Long Điền).',NULL,NULL,'published'),
  ('Bánh khọt Gốc Vú Sữa','food','vt',NULL,NULL,'14 Nguyễn Trường Tộ — bánh khọt nhân tôm trứ danh.',NULL,NULL,'published'),
  ('Lẩu cá đuối Hoàng Minh','food','vt',NULL,NULL,'44 Trương Công Định — lẩu cá đuối măng chua.',NULL,NULL,'published'),
  ('Bánh canh ghẹ','food','vt',NULL,NULL,'Bánh canh ghẹ topping đầy (Võ Thị Sáu/Tú Xương).',NULL,NULL,'published'),
  ('Hải sản Gành Hào','food','vt',NULL,NULL,'Nhà hàng hải sản view biển nổi tiếng.',NULL,NULL,'published');
